version: "3.9"
services:
  ussd:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm i -g pnpm && pnpm i && pnpm start"
    ports:
      - "8080:8080"
    volumes:
      - ../../apps/ussd:/app